highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://snowBlanket.github.io/
author: Jonghyun, Jin

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Jin's Portfolio
name: Jonghyun, Jin
email: 11rhddhd@gmail.com
email_full: 11rhddhd@gmail.com
website: github.io/snowBlanket
website_full: https://snowBlanket.github.io/sustain
github: trending
twitter: '-'
tel: '-'
tel_full: tel:+440000000000
google_maps: '-'
address:
  street: '-'
  postcode: '-'
  city: Suwon
  country: Republic of Korea
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
